version: "3"
services:
  app:
    container_name: app
    build: part5/.

  server:
    container_name: server
    image: nginx
    ports:
      - 80:8080
    build: part6/.
    links:
      - app





      